project_name: 3D_CLIP
clip_embed_dim: 1280
clip_embed_version: OpenCLIP
model:
  name: MinkResNet34 
  in_channel: 6
  out_channel: ${clip_embed_dim}
  embedding_channel: 1024
  voxel_size: 0.02

training:
  use_openclip_optimizer_scheduler: False
  use_openclip_loss: False
  local_loss: False
  gather_with_grad: False
  grad_clip_norm: null
  lr: 0.0005
  weight_decay: 0.2
  lr_decay_step: 10000
  lr_decay_rate: 0.95
  beta1: 0.9
  beta2: 0.999
  eps: 1.0e-8
  warmup: 10000
  max_epoch: 1000
  log_freq: 20
  save_freq: 200000
  lambda_img_contras: 1
  lambda_text_contras: 1
  use_image_proj: False 
  use_text_proj: False
  logit_scale_init: 14.28
  use_mask: False
  mask_threshold: 0.1

dataset:
  name: Four
  data_root: /path/to/openshape/objaverse-processed/
  train_split: /path/to/openshape/meta_data/split/train_all.json
  train_partial: -1
  num_points: 10000 
  num_workers: 6
  train_batch_size: 200
  test_batch_size: 100
  use_knn_negative_sample: False
  negative_sample_num: 1
  knn_path: /path/to/openshape/meta_data/point_feat_knn.npy
  y_up: True
  normalize: True
  random_z_rotate: True
  use_color: True
  rgb_random_drop_prob: 0.5
  augment: True
  text_source: [text, caption, retrieval_text] 
  use_text_filtering: True
  use_prompt_engineering: True
  gpt4_filtering_path: /path/to/openshape/meta_data/gpt4_filtering.json

modelnet40:
  test_split: /path/to/openshape/meta_data/modelnet40/test_split.json
  test_pc: /path/to/openshape/meta_data/modelnet40/test_pc.npy
  num_points: 10000 
  num_workers: 0
  test_batch_size: 64
  clip_feat_path: /path/to/openshape/meta_data/modelnet40/cat_name_pt_feat.npy
  y_up: True

objaverse_lvis:
    split: /path/to/openshape/meta_data/split/lvis.json
    clip_feat_path: /path/to/openshape/meta_data/lvis_cat_name_pt_feat.npy
    num_points: 10000 
    num_workers: 6
    batch_size: 64
    y_up: True
    normalize: True
    use_color: True

scanobjectnn:
  data_path: /path/to/openshape/meta_data/scanobjectnn/xyz_label.npy 
  num_points: 10000 
  num_workers: 0
  test_batch_size: 64
  clip_feat_path: /path/to/openshape/meta_data/scanobjectnn/cat_name_pt_feat.npy
  y_up: True
  